import type { CodegenPlugin, ContractArtifact, GeneratedFile } from '../types.js'

const DO_NOT_EDIT_HEADER = `// ============================================================
// THIS FILE IS AUTO-GENERATED BY @web3marketlabs/codegen
// DO NOT EDIT THIS FILE MANUALLY
// ============================================================
`

function formatAbiConstant(contractName: string, abi: readonly unknown[]): string {
  const varName = `${contractName.charAt(0).toLowerCase() + contractName.slice(1)}Abi`
  const abiJson = JSON.stringify(abi, null, 2)
  return `export const ${varName} = ${abiJson} as const\n`
}

function generateAbiFile(artifact: ContractArtifact): GeneratedFile {
  const content = [DO_NOT_EDIT_HEADER, formatAbiConstant(artifact.name, artifact.abi)].join('\n')
  return { path: `abis/${artifact.name}.ts`, content }
}

export const abiGeneratorPlugin: CodegenPlugin = {
  name: 'abi-generator',
  async generate(artifacts: ContractArtifact[]): Promise<GeneratedFile[]> {
    return artifacts.map(generateAbiFile)
  },
}

export { generateAbiFile, formatAbiConstant }
