import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type { CodegenPlugin, GeneratedFile } from '../types.js'

const DO_NOT_EDIT_HEADER = `// ============================================================
// THIS FILE IS AUTO-GENERATED BY @web3marketlabs/codegen
// DO NOT EDIT THIS FILE MANUALLY
// ============================================================
`

interface ChainDeployment { [contractName: string]: string }

async function readDeployments(deploymentsDir: string): Promise<Map<number, ChainDeployment>> {
  const deployments = new Map<number, ChainDeployment>()
  let files: string[]
  try { files = await fs.readdir(deploymentsDir) } catch { return deployments }

  for (const file of files) {
    if (!file.endsWith('.json')) continue
    const chainId = parseInt(file.replace('.json', ''), 10)
    if (isNaN(chainId)) continue
    try {
      const raw = await fs.readFile(path.join(deploymentsDir, file), 'utf-8')
      deployments.set(chainId, JSON.parse(raw) as ChainDeployment)
    } catch { continue }
  }
  return deployments
}

function buildContractRegistries(deployments: Map<number, ChainDeployment>): Map<string, Map<number, string>> {
  const registries = new Map<string, Map<number, string>>()
  for (const [chainId, contracts] of deployments) {
    for (const [contractName, address] of Object.entries(contracts)) {
      if (!registries.has(contractName)) registries.set(contractName, new Map())
      registries.get(contractName)!.set(chainId, address)
    }
  }
  return registries
}

function generateAddressesContent(registries: Map<string, Map<number, string>>): string {
  if (registries.size === 0) {
    return [DO_NOT_EDIT_HEADER, '// No deployments found.', ''].join('\n')
  }
  const lines: string[] = [DO_NOT_EDIT_HEADER]
  for (const contractName of Array.from(registries.keys()).sort()) {
    const chains = registries.get(contractName)!
    const varName = `${contractName.charAt(0).toLowerCase() + contractName.slice(1)}Addresses`
    const entries = Array.from(chains.entries())
      .sort(([a], [b]) => a - b)
      .map(([chainId, address]) => `  ${chainId}: '${address}'`)
      .join(',\n')
    lines.push(`export const ${varName} = {`, entries, `} as const satisfies Record<number, \`0x\${string}\`>`, '')
  }
  return lines.join('\n')
}

export function createAddressGeneratorPlugin(deploymentsDir: string): CodegenPlugin {
  return {
    name: 'address-generator',
    async generate(): Promise<GeneratedFile[]> {
      const deployments = await readDeployments(deploymentsDir)
      const registries = buildContractRegistries(deployments)
      return [{ path: 'addresses.ts', content: generateAddressesContent(registries) }]
    },
  }
}

export { readDeployments, buildContractRegistries, generateAddressesContent }
